{"name": "test_assertFault", "status": "passed", "attachments": [{"name": "stdout", "source": "5aa20fb6-65d6-45a7-95b7-c4c3bd7b3f04-attachment.txt", "type": "text/plain"}], "start": 1603087533963, "stop": 1603087533963, "uuid": "37964e7e-b84c-4c4e-8843-610c57ca28af", "historyId": "21b5f9d999996067280b0fee22a2342b", "testCaseId": "ef5aef7c0cb33c22f754dad21b655c17", "fullName": "test_unittest.TestMethods1#test_assertFault", "labels": [{"name": "suite", "value": "test_unittest"}, {"name": "subSuite", "value": "TestMethods1"}, {"name": "host", "value": "Yiron.local"}, {"name": "thread", "value": "87736-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_unittest"}]}